### ISSUE TITLE
V 1.2 makes bank apps crash 

### ISSUE THREAD

**Issue by elswerky** [Dr-TSNG/ZygiskOnKernelSU#156]
### Steps to reproduce/复现步骤

Hello 
I was using v 1.1 was zygisk disabled and lspsoed module and bank apps was working without crash on kitsune 

Then I flashed v 1.2 preview  of zygisk next  and found such bank apps crash 
So I reverted back to v1.1 and everything works well

Days ago I got an update to v 1.2 which is now supposed to be stable version but still bank apps crash with it 

So am sticking with v1.1 but don't want to miss new features 

### Expected behaviour/预期行为

Bank apps open without issue

### Actual behaviour / 实际行为

Crash of bank apps

### Module List / 模块列表

```Shell
Just
Zygisk next
Zygisk lspsoed
Automatic brick rescue
```

### Zygisk Next version / Zygisk Next 版本

V 1.2 vs V 1.1

### Android version / Android 版本

 A 13 , A14

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

Kitsune 27.001

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

Don't have logs

**Comment by Astoritin** [comment]
1. If you use Kitsune Mask instead of official Magisk / Magisk Alpha, please explore and find out the answer to hide root by yourself
2. Zygisk Next has nothing to do with hiding root, Zygisk Next only provides Zygisk API to Zygisk modules
3. If you don't provide logs, this issue can be only taken as spam (useless feedback), sounds good?

**Comment by Wirat2211** [comment]
Just
Zygisk next
Zygisk lspsoed
Automatic brick rescue

**Comment by Wirat2211** [comment]
https://github.com/Dr-TSNG/ZygiskNext/issues/156#issuecomment-2425460688
